from django.urls import path

from . import views
from . import admin_views
from .api_views import (
    CompleteQuizAPI,
    CurrentQuestionAPI,
    DashboardAPI,
    GenerateQuestionAPI,
    NextQuestionAPI,
    PerformanceAPI,
    QuizHistoryAPI,
    StartQuizAPI,
    SubmitAnswerAPI,
    TopicsAPI,
)

urlpatterns = [
    path("admin-panel/login/", admin_views.admin_login, name="admin_login"),
    path("admin-panel/logout/", admin_views.admin_logout, name="admin_logout"),
    path("admin-panel/", admin_views.admin_dashboard, name="admin_dashboard"),
    path("admin-panel/questions/", admin_views.admin_questions, name="admin_questions"),
    path("admin-panel/questions/add/", admin_views.admin_question_create, name="admin_question_create"),
    path("admin-panel/questions/<str:question_id>/edit/", admin_views.admin_question_edit, name="admin_question_edit"),
    path("admin-panel/questions/<str:question_id>/delete/", admin_views.admin_question_delete, name="admin_question_delete"),
    path("admin-panel/notes/", admin_views.admin_notes, name="admin_notes"),
    path("admin-panel/notes/add/", admin_views.admin_note_create, name="admin_note_create"),
    path("admin-panel/notes/<slug:language_slug>/<int:topic_index>/edit/", admin_views.admin_note_edit, name="admin_note_edit"),
    path("admin-panel/notes/<slug:language_slug>/<int:topic_index>/delete/", admin_views.admin_note_delete, name="admin_note_delete"),
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("select-quiz/", views.select_quiz, name="select_quiz"),
    path("quiz/", views.quiz_page, name="quiz_page"),
    path("quiz/prefetch/", views.prefetch_question, name="prefetch_question"),
    path("submit-answer/", views.submit_answer, name="submit_answer"),
    path("result/", views.quiz_result, name="quiz_result"),
    path("history/", views.quiz_history, name="history"),
    path("performance/", views.performance, name="performance"),
    path("technical-languages/", views.technical_languages, name="technical_languages"),
    path("technical-languages/<slug:language_slug>/", views.language_topics, name="language_topics"),
    path("technical-languages/<slug:language_slug>/topic/<int:topic_index>/", views.topic_notes, name="topic_notes"),
    path("technical-languages/<slug:language_slug>/topic/<int:topic_index>/practice/", views.practice_topic, name="practice_topic"),
    path("api/generate-question/", GenerateQuestionAPI.as_view(), name="contract_generate_question"),
    path("api/submit-answer/", SubmitAnswerAPI.as_view(), name="contract_submit_answer"),
    path("api/quiz/start/", StartQuizAPI.as_view(), name="api_quiz_start"),
    path("api/quiz/<int:quiz_id>/question/", CurrentQuestionAPI.as_view(), name="api_quiz_question"),
    path("api/quiz/<int:quiz_id>/next/", NextQuestionAPI.as_view(), name="api_quiz_next"),
    path("api/quiz/<int:quiz_id>/complete/", CompleteQuizAPI.as_view(), name="api_quiz_complete"),
    path("api/dashboard/", DashboardAPI.as_view(), name="contract_dashboard"),
    path("api/performance/", PerformanceAPI.as_view(), name="contract_performance"),
    path("api/quiz-history/", QuizHistoryAPI.as_view(), name="contract_quiz_history"),
    path("api/topics/", TopicsAPI.as_view(), name="contract_topics"),
]
