# Generated by Django 5.1.15 on 2026-09-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizattempt_selected_question_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_slug', models.SlugField(max_length=100)),
                ('language_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=150)),
                ('content', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['language_name', 'topic'],
                'constraints': [models.UniqueConstraint(fields=('language_slug', 'topic'), name='unique_technical_note_topic')],
            },
        ),
    ]
